require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/family_members", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FamilyMember. As you add validations to FamilyMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FamilyMember.create! valid_attributes
      get family_members_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      family_member = FamilyMember.create! valid_attributes
      get family_member_url(family_member)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_family_member_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      family_member = FamilyMember.create! valid_attributes
      get edit_family_member_url(family_member)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FamilyMember" do
        expect {
          post family_members_url, params: { family_member: valid_attributes }
        }.to change(FamilyMember, :count).by(1)
      end

      it "redirects to the created family_member" do
        post family_members_url, params: { family_member: valid_attributes }
        expect(response).to redirect_to(family_member_url(FamilyMember.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FamilyMember" do
        expect {
          post family_members_url, params: { family_member: invalid_attributes }
        }.to change(FamilyMember, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post family_members_url, params: { family_member: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested family_member" do
        family_member = FamilyMember.create! valid_attributes
        patch family_member_url(family_member), params: { family_member: new_attributes }
        family_member.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the family_member" do
        family_member = FamilyMember.create! valid_attributes
        patch family_member_url(family_member), params: { family_member: new_attributes }
        family_member.reload
        expect(response).to redirect_to(family_member_url(family_member))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        family_member = FamilyMember.create! valid_attributes
        patch family_member_url(family_member), params: { family_member: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested family_member" do
      family_member = FamilyMember.create! valid_attributes
      expect {
        delete family_member_url(family_member)
      }.to change(FamilyMember, :count).by(-1)
    end

    it "redirects to the family_members list" do
      family_member = FamilyMember.create! valid_attributes
      delete family_member_url(family_member)
      expect(response).to redirect_to(family_members_url)
    end
  end
end
